### ISSUE TITLE
Create data importer class

### ISSUE THREAD

**Issue by jkoscialkowski** [jkoscialkowski/gsn-projekt#1]

**Comment by michaljaworski259** [comment]
`python3 downloader.py -T stocks -E NYQ`

Run above line in terminal to download and save in `csv` files all of the stock prices from NYSE in the directory `./all_values/stocks/NYQ`

List of all stock exchanges for the specific types of quotations can be found in `csv` files here: [https://github.com/jkoscialkowski/gsn-projekt/tree/master/amphibian/fetch/data](url)
