### ISSUE TITLE
Move all data from Dictionaries ---> Tensors in TimeSeriesData class

### ISSUE THREAD

**Issue by michaljaworski259** [jkoscialkowski/gsn-projekt#41]

**Comment by jkoscialkowski** [comment]
I think we should switch to using TensorDataset, it seems to support supplying X's and y's separately and would probably be faster if supplied with the full X and y tensors.
[https://stackoverflow.com/questions/41924453/pytorch-how-to-use-dataloaders-for-custom-datasets](https://stackoverflow.com/questions/41924453/pytorch-how-to-use-dataloaders-for-custom-datasets)
